### ISSUE TITLE
Scroll doesn't appear in search list

### ISSUE THREAD

**Issue by munhigh** [praveenn77/docusaurus-lunr-search#139]
I applied docusaurus-lunr-search using the method you provided. First of all, thank you.

Afterwards, we searched by adding the maxHits option and confirmed that the number of items in the list increased. At this time, if there are too many search results, the items below are not displayed (the problem is that the search result list is longer than the web page).
In this case, is there a way to add scrolling to the search list?

![scroll](https://github.com/praveenn77/docusaurus-lunr-search/assets/135942398/75157aee-eaad-477e-b86d-ad4d33faf47e)

**Comment by quantifex** [comment]
@munhigh If you're still looking for an option on this, I just solved this on our setup with some custom CSS, specifically this block:
```css
.algolia-autocomplete .ds-dropdown-menu .ds-suggestions {
  overflow-y: scroll;
  height: 100vh;
}
```
Note: This `height: 100vh;` bit is required to get the scrollable area to honor just the viewable height.
