### ISSUE TITLE
Dark Theme support

### ISSUE THREAD

**Issue by xf-** [praveenn77/docusaurus-lunr-search#55]
At the moment, i overwrite the style, but the variables from docusaurus should be used like i do and the support is integrated and match the colors from the project.

_This id far from perfect, but no a bright overlay anymore_
```css
html[data-theme='dark'] .algolia-docsearch-suggestion--category-header,
html[data-theme='dark'] .algolia-docsearch-suggestion--wrapper,
html[data-theme='dark'] .algolia-docsearch-footer {
    background: var(--ifm-background-color);
    color: var(--ifm-font-color-base);
}

html[data-theme='dark'] .algolia-docsearch-suggestion--title {
    color: var(--ifm-font-color-base);
}

html[data-theme='dark'] .ds-cursor .algolia-docsearch-suggestion--wrapper {
    background: var(--ifm-background-surface-color);
}
```
